mkdir -p bundle
cd bundle

git clone git://github.com/garbas/vim-snipmate.git
git clone https://github.com/tomtom/tlib_vim.git
git clone https://github.com/MarcWeber/vim-addon-mw-utils.git
git clone https://github.com/honza/snipmate-snippets.git
#git clone https://github.com/wincent/Command-T.git
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/ervandew/supertab.git
git clone https://github.com/tpope/vim-surround
git clone https://github.com/mattn/zencoding-vim.git
git clone https://github.com/scrooloose/syntastic.git
git clone https://github.com/sukima/xmledit.git
git clone https://github.com/vim-scripts/vcscommand.vim.git
git clone https://github.com/kchmck/vim-coffee-script.git
git clone https://github.com/vim-scripts/ASPJScript.git
git clone https://github.com/plasticboy/vim-markdown.git
git clone https://github.com/marzocchi/vim-color-picker-osx.git
#git clone https://github.com/jelera/vim-javascript-syntax
#git clone https://github.com/othree/javascript-syntax.vim.git
git clone https://github.com/mileszs/ack.vim.git
#git clone https://github.com/amigrave/vim-pudb
git clone https://github.com/tpope/vim-commentary
git clone https://github.com/dmitry-ilyashevich/vim-typescript.git
git clone git://github.com/digitaltoad/vim-jade.git
git clone https://github.com/wavded/vim-stylus.git
git clone https://github.com/rainux/vim-vala.git
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/evanmiller/nginx-vim-syntax.git
git clone https://github.com/Glench/Vim-Jinja2-Syntax.git
